DROP TABLE IF EXISTS stickers;
DROP TABLE IF EXISTS sizes;
DROP TABLE IF EXISTS aspects;

CREATE TABLE sizes (
	id SERIAL PRIMARY KEY,
	name VARCHAR(20) UNIQUE NOT NULL,
	logical_order SMALLINT NOT NULL
);

CREATE TABLE aspects (
	id SERIAL PRIMARY KEY,
	name VARCHAR(20) UNIQUE NOT NULL,
	logical_order SMALLINT NOT NULL
);

CREATE TABLE stickers (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	description VARCHAR(1000) NOT NULL,
	image_url VARCHAR(300) UNIQUE NOT NULL,
	price DECIMAL(5, 2) NOT NULL,
	size_id INTEGER REFERENCES sizes(id) NOT NULL,
	aspect_id INTEGER REFERENCES aspects(id) NOT NULL,
	date_added DATE NOT NULL
);
